ALTER TABLE inquiries ADD COLUMN venue TEXT NOT NULL DEFAULT '';
ALTER TABLE inquiries ADD COLUMN coverage TEXT NOT NULL DEFAULT '';
ALTER TABLE inquiries ADD COLUMN priorities TEXT NOT NULL DEFAULT '';
ALTER TABLE inquiries ADD COLUMN referral_source TEXT NOT NULL DEFAULT '';
ALTER TABLE inquiries ADD COLUMN contact_preference TEXT NOT NULL DEFAULT '';
